@startuml

!define BORDER #3FBC5F
!define LINE #3FBC5F

skinparam {
Shadowing false
  roundcorner 15
}
skinparam sequence {
	ArrowColor LINE
	ActorBorderColor BORDER
	LifeLineBorderColor LINE
	LifeLineBackgroundColor white
  
	ParticipantBorderColor BORDER
	ParticipantBackgroundColor white
  
	ActorBackgroundColor white
}

@enduml
